name: reusable workflow for test execustion

on:
  workflow_call:

jobs:
  test:
    name: test execution
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: ruby raj0522/test01/main/test.rb
